classDiagram
direction LR

class Usuario {
  +int id_usuario
  +String nome
  +String email
}

class Pergunta {
  +int id_pergunta
  +String texto
  +Date data_criacao
  +int id_usuario
}

class Resposta {
  +int id_resposta
  +String texto
  +Date data_criacao
  +int id_pergunta
  +int id_usuario
}

class Tag {
  +int id_tag
  +String nome
}

class PerguntaTag {
  +int id_pergunta
  +int id_tag
}

class Voto {
  +int id_voto
  +int valor
  +int id_usuario
  +int id_pergunta
}

Usuario "1" --> "0..*" Pergunta : publica
Usuario "1" --> "0..*" Resposta : escreve
Pergunta "1" *-- "0..*" Resposta : possui
Pergunta "1" --> "0..*" PerguntaTag : possui
Tag "1" --> "0..*" PerguntaTag : classifica
Usuario "1" --> "0..*" Voto : registra
Pergunta "1" *-- "0..*" Voto : recebe